kind: Service
apiVersion: v1
metadata:
  name: np-postgresql
  namespace: sso
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: sso-postgresql
  type: NodePort
