apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bash
spec:
  workspaces:
  - name: storage
    readOnly: false
  params:
  - name: command
  steps:
  - name: run-command
    image: fedora
    script: cd $(workspaces.storage.path); chmod -R 777 $(workspaces.storage.path); $(params.command)