apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-build
spec:
  workspaces:
  - name: shared-workspace
  - name: maven-settings
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: master
  - name: APP_PROFILE
    description: >-
      The application profile to use for building the application. In this example it should be either:
        * quarkus
        * springboot    
  - name: CONTEXT_DIR
    type: string
    description: folder in git repo where source is
  - name: command
    type: string
    default: 'ls -ltr'    
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: list-filesystem
    taskRef:
      name: run-script
      kind: Task
    workspaces:
    - name: storage
      workspace: shared-workspace
    params:
    - name: script
      value: |
        #!/usr/bin/env bash
        set -xe
        echo "Script running in $(workspaces.storage.path)"
        chmod -R 777 $(workspaces.storage.path)
        ls -ltr $(workspaces.storage.path)
        echo "$(workspaces.storage.path)/src/settings.xml : "
        cat $(workspaces.storage.path)/src/settings.xml 
    runAfter:
      - fetch-repository    
  - name: test-java-app
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - list-filesystem
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: GOALS
        value:
          - -U 
          - -Dspring.profiles.active=dev
          - -B
          - 'clean'
          - 'test'
    workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: shared-workspace
  - name: build-java-app
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - test-java-app
    params:
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR)
      - name: GOALS
        value:
          - -U 
          - -Dmaven.wagon.http.ssl.insecure=true 
          - -Dmaven.wagon.http.ssl.allowall=true
          - -B
          - '-DskipTests'
          - 'clean'
          - 'deploy'
    workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: shared-workspace
  - name: buildah-image
    taskRef:
      name: buildah
    runAfter:
      - build-java-app
    params:
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/tekton-test/inventory
      - name: CONTEXT_DIR
        value: $(params.CONTEXT_DIR) 
      - name: TLSVERIFY
        value: 'false'
    workspaces:
      - name: source
        workspace: shared-workspace                