spring:
  application:
    name: shop.build.test

server:
  port: 8080
  connect-timeout: 360000

basket:
  host: basket.amazin-dev.svc:8080

inventory:
  host: inventory.amazin-dev.svc:8080

user:
  host: user.amazin-dev.svc:8080

