apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: amazin-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key      
    hosts:
    - "amazin-istio-system.apps.ocp4.openshiftlabs.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: amazin-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - amazin-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: api-gateway-prd
        port:
          number: 8080