apiVersion: apps.m88i.io/v1alpha1
kind: Nexus
metadata:
  name: nexus3
  namespace: cicd
spec:
  serviceAccountName: nexus3
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 240
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
  useRedHatImage: true
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 240
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
  serverOperations: {}
  automaticUpdate:
    disabled: true
  networking:
    expose: true
    exposeAs: Route
    tls:
      mandatory: true
  image: registry.connect.redhat.com/sonatype/nexus-repository-manager
  replicas: 1
  persistence:
    persistent: true
    storageClass: nfs-client
    volumeSize: 100Gi