apiVersion: capabilities.3scale.net/v1beta1
kind: OpenAPI
metadata:
  name: sso-product-openapi2
  namespace: 3scale
spec:
  openapiRef:
    url: https://inventory-tekton-test.apps.sno.openshiftlabs.net/v3/api-docs
  productSystemName: sso-product-openapi
  stagingPublicBaseURL: 'https://sso-product-staging-3scale.apps.sno.openshiftlabs.net'
  productionPublicBaseURL: 'https://sso-product-3scale.apps.sno.openshiftlabs.net' 
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sso-product-staging
  namespace: 3scale
spec:
  host: sso-product-staging-3scale.apps.sno.openshiftlabs.net
  to:
    kind: Service
    name: apicast-staging
    weight: 100
  port:
    targetPort: gateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sso-product-production
  namespace: 3scale
spec:
  host: sso-product-3scale.apps.sno.openshiftlabs.net
  to:
    kind: Service
    name: apicast-production
    weight: 100
  port:
    targetPort: gateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None     